In [29]:
import sklearn
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Similarity between two sentences

In this notebook, **cosine similarity** between two sentences is computed with following steps:

### Steps: 

#### Method 1

1. Convert words into vector of numbers using bag of words (It returns count of the word in sentence based on all vocabulary words.

2. After converting words to vector form, we can directly compute cosine similarity b/w two vectors 

3. Then compute dot product.

**Note**: Bag of words does not account for semantic similarity, for example: two sentences: "Marry is quicker than John" and "John is quicker than Marry" are same when we use bag of words rather than word embeddings

#### Method 2

1. Convert words into vector of numbers using bag of words (It returns count of the word in sentence based on all vocabulary words.

2. Apply TF-IDF to the result of bag of words for assign weight to each term. 

3. Then compute cosine similarity and dot product.


In [79]:
class TextSimilarity():
    
    def __init__(self):
        pass
    
    # convert words into numbers
    def applyBagofWords(self, data):
        
        vectorizer = CountVectorizer()
        return vectorizer.fit_transform(data).toarray()
    
    def applyTfIDF(self, data):
        
        vectorizer = TfidfVectorizer()
        tf = vectorizer.fit_transform(data).toarray()
        return tf 
    
    def computeCosineSimilarity(self, vectors):
        
        return cosine_similarity(vectors)
        
    def computeDotProduct(self, v1, v2):
        
        return np.dot(v1, v2)
    
textSim = TextSimilarity()
data_corpus = ["Marry and John are very good friends", "Jack and Martin are enemies"]
print ("Bag of words vector \n")
print (textSim.applyBagofWords(data_corpus))
tf_idf_vectors = textSim.applyTfIDF(data_corpus)
print (" \n ==== TF IDF ====== \n")
print (tf_idf_vectors)
print ( " \n ==== cosine similarity ==== \n ")
cosine_sim = textSim.computeCosineSimilarity(tf_idf_vectors)
print (cosine_sim)
print (" \n ==== dot product === \n ")
print (textSim.computeDotProduct(cosine_sim[0], cosine_sim[1]))

Bag of words vector 

[[1 1 0 1 1 0 1 1 0 1]
 [1 1 1 0 0 1 0 0 1 0]]
 
 ==== TF IDF ====== 

[[0.29017021 0.29017021 0.         0.4078241  0.4078241  0.
  0.4078241  0.4078241  0.         0.4078241 ]
 [0.35520009 0.35520009 0.49922133 0.         0.         0.49922133
  0.         0.         0.49922133 0.        ]]
 
 ==== cosine similarity ==== 
 
[[1.         0.20613697]
 [0.20613697 1.        ]]
 
 ==== dot product === 
 
0.41227393213657215
